config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'events/index'

  get 'events/new'

  get 'events/create'

  #get 'events/show'

  get 'events/:id' => 'events#show'
  resources :tickets

  root :to => "tickets#index"

  resources :events


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :artist, :presence => true,
            :length => {:minimum => 6}
  validates :price_low, numericality: true,
            :presence => true
  validates :price_high, numericality: true,
            :presence => true
  validates :event_date,
            :presence => true

  validate :event_date_not_from_past
  validate :price_low_less_than_price_high

  has_many :tickets

  def event_date_not_from_past
    if event_date && (event_date < Date.today)
      errors.add('Data wydarzenia', 'nie moze byc z przeszlosci')
    end
  end

  def price_low_less_than_price_high
    if price_low && (price_high && price_low > price_high)
      errors.add('Minimalna cena', 'nie moze byc nizsza od maksymalnej')
    end
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, :presence => true,
            :length => {:minimum => 6}
  validates :email_address, format: {with: URI::MailTo::EMAIL_REGEXP},
            :presence => true
  validates :price,
            :presence => true
  validates :seat_id_seq,
            :presence => true
  validates :address,
            :presence => true
  validate :price_in_range

  belongs_to :event
  belongs_to :user

  def price_in_range
    print("price validator")
    event = Event.find(event_id)
    if price && (price < event.price_low || price > event.price_high)
      errors.add('Cena', 'nie moze byc nizsza od minimalnej lub wieksza od maksymalnej')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_logged_in, :only => [:new, :create]
  before_action :set_event, only: [:show]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = Event.new
  end

  def create
    event_parmas = params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)

    @event = Event.new(event_parmas)
    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end
  end

  private

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "michal" && password == "michal"
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new(:user_id => current_user.id)
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    puts ticket_params.inspect
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
  end

  def correct_user
    @ticket = current_user.tickets.find_by(id: params[:id])
    redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.text_field :price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.text_field :price_high %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.text_field :event_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_new_ticket.html.erb
<h1>New Ticket</h1>

<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group">
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :seat_id_seq %>
        <%= form.text_field :seat_id_seq, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :address %>
        <%= form.text_field :address, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :email_address %>
        <%= form.text_field :email_address, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.label :phone %>
        <%= form.text_field :phone, :class => 'form-control' %>
      </div>
      <div class="field">
        <%= form.hidden_field :event_id %>
      </div>

      <div class="field">
        <%= form.hidden_field :user_id %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </form>

<% end %>

app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Seat id seq</th>
    <th>Address</th>
    <th>Price</th>
    <th>Email address</th>
    <th>Phone</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.name %></td>
      <td><%= ticket.seat_id_seq %></td>
      <td><%= ticket.address %></td>
      <td><%= ticket.price %></td>
      <td><%= ticket.email_address %></td>
      <td><%= ticket.phone %></td>
      <td><button><%= link_to 'Show', ticket %></button></td>
      <td><button><%= link_to 'Edit', edit_ticket_path(ticket) %></button></td>
      <td><button><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/events/index.html.erb
<h1> Wszystkie wydarzenia</h1>
<p></p>
<div class="list-group">
  <% for event in @events %>
    <%= link_to event.artist, "/events/#{event.id}", :class => "list-group-item list-group-item-action list-group-item-primary" %>
  <% end %>

</div>
<p></p>
<div>
  <% if user_signed_in? %>
    <%= link_to 'Nowe ogłoszenie', events_new_path, :class => "btn btn-primary" %>
  <% end %>
  <%= link_to 'Cofnij', "/", :class => "btn btn-primary" %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="komunikat"><%= flash[:komunikat] %></p>
<p id="notice"><%= notice %></p>

<ul class="list-group">
  <li class="list-group-item">
    <strong>Artist:</strong>
    <%= @event.artist %>
  </li>
  <li class="list-group-item">
    <strong>Description:</strong>
    <%= @event.description %>
  </li>
  <li class="list-group-item">
    <strong>Price low:</strong>
    <%= @event.price_low %>
  </li>
  <li class="list-group-item">
    <strong>Price high:</strong>
    <%= @event.price_high %></li>
  <li class="list-group-item">
    <strong>Event date:</strong>
    <%= @event.event_date %>
  </li>
</ul>

<% if user_signed_in? %>
  <%= render "new_ticket", ticket: Ticket.new(:event_id => @event.id, :user_id => current_user.id) %>
<% end %>

<%= render "tickets_list", tickets: @event.tickets %>

<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Organizacja Eventów</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>app
<% end %>

<nav class="navbar navbar-light bg-light">
  <% if user_signed_in? %>
  <a class="navbar-brand" href="/">Logged in as <strong><%= current_user.email %></strong>.</a>
  <% end %>
  <form class="form-inline">
    <% if user_signed_in? %>

      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-outline-primary' %>
      <div style="padding-left: 10px;">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-outline-danger' %>
      </div>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
  </form>
</nav>
<%= yield %>
</body>
</html>

app/views/tickets/_events_list.html.erb
<h1> Wydarzenia</h1>

<table>
  <thead>
  <tr>
    <th>Id</th>
    <th>Artist</th>
    <th>Description</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% events.each do |event| %>
    <tr>
      <td><%= event.id %></td>
      <td><%= event.artist %></td>
      <td><%= event.description %></td>
      <td><%= link_to 'Show', "/events/#{event.id}" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.label :phone_field %>
    <%= form.text_field :phone_field, id: :ticket %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Event:</strong>
  <%= link_to @ticket.event_id, "/events/#{@ticket.event_id}" %>
</p>

<% if @ticket.user == current_user %>
  <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>
<%= link_to 'Back', tickets_path %>